dist: trusty
sudo: required

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

language: node_js
node_js:
  - '6.11.0'

before_script:
  - 'npm install grunt --save-dev'
  - 'npm install grunt-karma --save-dev'
  - 'npm install grunt-build-control --save-dev'
  - 'npm install time-grunt --save-dev'
  - 'npm install jit-grunt --save-dev'
  - 'npm install grunt-contrib-clean --save-dev'
  - 'npm install jshint-stylish --save-dev'
  - 'npm install autoprefixer-core --save-dev'
  - 'npm install grunt-cli --save-dev'
  - 'npm install grunt-wiredep --save-dev'
  - 'npm install grunt-concurrent --save-dev'
  - 'npm install grunt-postcss --save-dev'
  - 'npm install grunt-contrib-connect --save-dev'
  - 'npm install grunt-contrib-watch --save-dev'
  - 'npm install grunt-contrib-copy --save-dev'
  - 'npm install karma --save-dev'
  - 'npm install karma-chrome-launcher --save-dev'
  - 'npm install karma-jasmine --save-dev'
  - 'npm install karma-junit-reporter --save-dev'
  - 'npm install jasmine-core --save-dev'


