sudo: required
dist: trusty

language: node_js
node_js:
  - '6.11.0'

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable

before_script:
  - 'npm install grunt --save-dev'
  - 'npm install grunt-karma --save-dev'
  - 'npm install grunt-build-control --save-dev'
  - 'npm install time-grunt --save-dev'
  - 'npm install jit-grunt --save-dev'
  - 'npm install grunt-contrib-clean --save-dev'
  - 'npm install jshint-stylish --save-dev'
  - 'npm install autoprefixer-core --save-dev'
  - 'npm install grunt-cli --save-dev'
  - 'npm install grunt-wiredep --save-dev'
  - 'npm install grunt-concurrent --save-dev'
  - 'npm install grunt-postcss --save-dev'
  - 'npm install grunt-contrib-connect --save-dev'
  - 'npm install grunt-contrib-watch --save-dev'
  - 'npm install grunt-contrib-copy --save-dev'
  - 'npm install karma --save-dev'
  - 'npm install karma-chrome-launcher --save-dev'
  - 'npm install karma-jasmine --save-dev'
  - 'npm install karma-junit-reporter --save-dev'


